### ISSUE TITLE
Cannot build, app.js not generated

### ISSUE THREAD

**Issue by kino90** [dwightjack/umeboshi-template-webpack#1]
When scaffolding a new project, it won't create the `js` folder (and the app.js file), resulting in an error while doing a `yarn start`

Error: `Module not found: Error: Can't resolve './app\assets\js/app.js' in 'C:\Dev\ume\test'`

**Comment by kino90** [comment]
Full error: 
```
ERROR in multi eventsource-polyfill webpack-dev-server/client?http://192.168.11.75:8000 ./app/assets/styles/index.js ./app/assets/js/app.js
Module not found: Error: Can't resolve './app\assets\js/app.js' in 'C:\Dev\ume\test'
 @ multi eventsource-polyfill webpack-dev-server/client?http://192.168.11.75:8000 ./app/assets/styles/index.js ./app/assets/js/app.js
```

Win 10, npm 6.10.3 64b

**Comment by dwightjack** [comment]
@kino90 thanks for debugging the template in Windows. 😢 (joking)

Will look into it!

**Comment by dwightjack** [comment]
Hi,

published a fix to umeboshi packages that _should_ work. 
I'm unable to test it on Windows due to some issues with node-sass.

To update the packages run in your project folder:

```
npm install umeboshi-config@0.1.9 umeboshi-scripts@0.1.8 --save-dev
```

**Comment by dwightjack** [comment]
Fixed by https://github.com/dwightjack/umeboshi-cli/releases/tag/3.0.4
